# Generated by Django 6.0.2 on 2026-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("pdf_file", models.FileField(upload_to="uploads/pdfs/")),
                (
                    "prompt",
                    models.TextField(
                        help_text="The prompt sent to the vision model for each page."
                    ),
                ),
                (
                    "max_pages",
                    models.PositiveIntegerField(
                        default=0, help_text="Max pages to process. 0 = all pages."
                    ),
                ),
                (
                    "markdown_file",
                    models.FileField(blank=True, null=True, upload_to="outputs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of pages in the PDF.",
                        null=True,
                    ),
                ),
                (
                    "pages_processed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of pages transcribed so far."
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "vision_backend",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "vision_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
