# Generated by Django 6.0.2 on 2026-02-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversiontask",
            name="max_pages",
        ),
        migrations.AddField(
            model_name="conversiontask",
            name="end_page",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Last page to process (0 = last page of the document).",
            ),
        ),
        migrations.AddField(
            model_name="conversiontask",
            name="start_page",
            field=models.PositiveIntegerField(
                default=1, help_text="First page to process (1-based)."
            ),
        ),
    ]
