# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0002_remove_conversiontask_max_pages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversiontask",
            name="failed_pages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {page: int, error: str} for pages that failed transcription.",
            ),
        ),
    ]
