# Generated by Django 6.0.2 on 2026-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0004_add_page_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vision_backend",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Override VISION_BACKEND: 'openai', 'gemini', or empty for env default.",
                        max_length=20,
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Override OpenAI model ID when backend is openai.",
                        max_length=100,
                    ),
                ),
                (
                    "gemini_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Override Gemini model ID when backend is gemini.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "App settings",
                "verbose_name_plural": "App settings",
            },
        ),
        migrations.AlterField(
            model_name="conversiontask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("partial_success", "Partially OK"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
